/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  const val com_eden_orchidplugin_gradle_plugin: String =
      "com.eden.orchidPlugin:com.eden.orchidPlugin.gradle.plugin:" +
      Versions.com_eden_orchidplugin_gradle_plugin

  /**
   * https://javaeden.github.io/Clog/Clog4j
   */
  const val clog4j: String = "com.eden:Clog4j:" + Versions.clog4j

  /**
   * https://javaeden.github.io/Common/Common
   */
  const val com_eden_common: String = "com.eden:Common:" + Versions.com_eden_common

  const val shadow: String = "com.github.jengelman.gradle.plugins:shadow:" + Versions.shadow

  const val gradle_bintray_plugin: String = "com.jfrog.bintray.gradle:gradle-bintray-plugin:" +
      Versions.gradle_bintray_plugin

  const val buildsrcversions: String = "de.fayard:buildSrcVersions:" + Versions.buildsrcversions

  /**
   * https://javaeden.github.io/Orchid/latest/core/
   */
  const val orchidcopper: String = "io.github.javaeden.orchid:OrchidCopper:" +
      Versions.io_github_javaeden_orchid

  /**
   * https://javaeden.github.io/Orchid/latest/core/
   */
  const val orchiddocs: String = "io.github.javaeden.orchid:OrchidDocs:" +
      Versions.io_github_javaeden_orchid

  /**
   * https://javaeden.github.io/Orchid/latest/core/
   */
  const val orchidgithub: String = "io.github.javaeden.orchid:OrchidGithub:" +
      Versions.io_github_javaeden_orchid

  const val orchidkotlindoc: String = "io.github.javaeden.orchid:OrchidKotlindoc:" +
          Versions.io_github_javaeden_orchid

  /**
   * https://javaeden.github.io/Orchid/latest/core/
   */
  const val orchidplugindocs: String = "io.github.javaeden.orchid:OrchidPluginDocs:" +
      Versions.io_github_javaeden_orchid

  /**
   * https://strikt.io/
   */
  const val strikt_core: String = "io.strikt:strikt-core:" + Versions.strikt_core

  /**
   * https://groovy-lang.org
   */
  const val groovy_all: String = "org.codehaus.groovy:groovy-all:" + Versions.groovy_all

  const val dokka_fatjar: String = "org.jetbrains.dokka:dokka-fatjar:" +
      Versions.org_jetbrains_dokka

  const val org_jetbrains_dokka_gradle_plugin: String =
      "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:" + Versions.org_jetbrains_dokka

  const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_scripting_compiler_embeddable: String =
      "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_serialization_unshaded: String =
      "org.jetbrains.kotlin:kotlin-serialization-unshaded:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_serialization: String = "org.jetbrains.kotlin:kotlin-serialization:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://github.com/Kotlin/kotlinx.serialization
   */
  const val kotlinx_serialization_runtime: String =
      "org.jetbrains.kotlinx:kotlinx-serialization-runtime:" +
      Versions.kotlinx_serialization_runtime

  /**
   * https://jsoup.org/
   */
  const val jsoup: String = "org.jsoup:jsoup:" + Versions.jsoup

  /**
   * https://junit.org/junit5/
   */
  const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:" +
      Versions.org_junit_jupiter

  /**
   * https://junit.org/junit5/
   */
  const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:" +
      Versions.org_junit_jupiter
}
