import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val com_eden_orchidplugin_gradle_plugin: String = "0.17.1" // available: "0.17.4"

  const val clog4j: String = "2.0.7"

  const val com_eden_common: String = "1.11.4"

  const val shadow: String = "5.1.0"

  const val gradle_bintray_plugin: String = "1.8.4"

  const val buildsrcversions: String = "0.4.2"

  const val io_github_javaeden_orchid: String = "0.20.0"

  const val strikt_core: String = "0.21.1"

  const val groovy_all: String = "2.5.8"

  const val org_jetbrains_dokka: String = "0.9.18"

  const val org_jetbrains_kotlin: String = "1.3.50"

  const val kotlinx_serialization_runtime: String = "0.12.0"

  const val jsoup: String = "1.12.1"

  const val org_junit_jupiter: String = "5.5.1"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "5.6.1"

  const val gradleCurrentVersion: String = "5.6"
}
